use strict;
use warnings;
package IO::Iron::Applications;

# ABSTRACT: Command line tools for package IO::Iron

our $VERSION = '0.10'; # VERSION: generated by DZP::OurPkgVersion

1;

__END__

=pod

=encoding UTF-8

=head1 NAME

IO::Iron::Applications - Command line tools for package IO::Iron

=head1 VERSION

version 0.10

=head1 AUTHOR

Mikko Koivunalho <mikko.koivunalho AT iki.fi>

=head1 BUGS

Please report any bugs or feature requests to bug-io-iron-applications@rt.cpan.org or through the web interface at:
 http://rt.cpan.org/Public/Dist/Display.html?Name=IO-Iron-Applications

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2014 by Mikko Koivunalho.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

The full text of the license can be found in the
F<LICENSE> file included with this distribution.

=cut
