---
abstract: 'Command line tools for package IO::Iron'
author:
  - 'Mikko Koivunalho <mikko.koivunalho AT iki.fi>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Iron-Applications
requires:
  App::Cmd::Setup: 0
  Carp: 0
  Carp::Assert: 0
  Carp::Assert::More: 0
  Data::Dumper: 0
  Data::UUID: 0
  English: 0
  Exception::Class: 0
  HTTP::Status: 0
  Hash::Util: 0.06
  IO::Iron::Common: 0
  IO::Iron::IronCache::Cache: 0
  IO::Iron::IronCache::Client: 0
  IO::Iron::IronCache::Item: 0
  JSON::MaybeXS: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Log::Log4perl: 0
  Log::Log4perl::Level: 0
  Parallel::Loops: 0
  Params::Validate: 0
  Scalar::Util: 0
  Template: 0
  Try::Tiny: 0
  URI::Escape: 0
  constant: 0
  parent: 0
  perl: 5.010_000
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IO-Iron-Applications
  homepage: https://metacpan.org/release/IO-Iron-Applications
  repository: https://github.com/mikkoi/io-iron-applications.git
version: 0.10
